# Game Data for Ticket to Ride - Matching Flutter app data

# Cities data - matching the Flutter app exactly
GAME_CITIES = [
    # Western Cities
    {"id": "vancouver", "name": "Vancouver", "x": 0.1, "y": 0.2, "region": "west"},
    {"id": "calgary", "name": "Calgary", "x": 0.2, "y": 0.15, "region": "west"},
    {"id": "helena", "name": "Helena", "x": 0.25, "y": 0.25, "region": "west"},
    {"id": "winnipeg", "name": "Winnipeg", "x": 0.35, "y": 0.2, "region": "west"},
    {"id": "duluth", "name": "Duluth", "x": 0.4, "y": 0.3, "region": "west"},
    {"id": "seattle", "name": "Seattle", "x": 0.1, "y": 0.3, "region": "west"},
    {"id": "portland", "name": "Portland", "x": 0.08, "y": 0.4, "region": "west"},
    {"id": "san_francisco", "name": "San Francisco", "x": 0.05, "y": 0.6, "region": "west"},
    {"id": "los_angeles", "name": "Los Angeles", "x": 0.1, "y": 0.75, "region": "west"},
    {"id": "las_vegas", "name": "Las Vegas", "x": 0.15, "y": 0.7, "region": "west"},
    {"id": "salt_lake_city", "name": "Salt Lake City", "x": 0.2, "y": 0.6, "region": "west"},
    {"id": "denver", "name": "Denver", "x": 0.3, "y": 0.55, "region": "west"},
    {"id": "phoenix", "name": "Phoenix", "x": 0.2, "y": 0.8, "region": "west"},
    {"id": "santa_fe", "name": "Santa Fe", "x": 0.3, "y": 0.75, "region": "west"},
    {"id": "el_paso", "name": "El Paso", "x": 0.35, "y": 0.85, "region": "west"},
    
    # Central Cities
    {"id": "kansas_city", "name": "Kansas City", "x": 0.45, "y": 0.5, "region": "central"},
    {"id": "oklahoma_city", "name": "Oklahoma City", "x": 0.45, "y": 0.65, "region": "central"},
    {"id": "dallas", "name": "Dallas", "x": 0.5, "y": 0.75, "region": "central"},
    {"id": "houston", "name": "Houston", "x": 0.5, "y": 0.85, "region": "central"},
    {"id": "little_rock", "name": "Little Rock", "x": 0.55, "y": 0.65, "region": "central"},
    {"id": "new_orleans", "name": "New Orleans", "x": 0.6, "y": 0.8, "region": "central"},
    {"id": "nashville", "name": "Nashville", "x": 0.65, "y": 0.6, "region": "central"},
    {"id": "atlanta", "name": "Atlanta", "x": 0.7, "y": 0.7, "region": "central"},
    {"id": "charleston", "name": "Charleston", "x": 0.75, "y": 0.75, "region": "central"},
    {"id": "miami", "name": "Miami", "x": 0.8, "y": 0.9, "region": "central"},
    
    # Eastern Cities
    {"id": "sault_st_marie", "name": "Sault St. Marie", "x": 0.5, "y": 0.25, "region": "east"},
    {"id": "toronto", "name": "Toronto", "x": 0.6, "y": 0.3, "region": "east"},
    {"id": "montreal", "name": "Montreal", "x": 0.7, "y": 0.25, "region": "east"},
    {"id": "boston", "name": "Boston", "x": 0.8, "y": 0.35, "region": "east"},
    {"id": "new_york", "name": "New York", "x": 0.8, "y": 0.45, "region": "east"},
    {"id": "washington", "name": "Washington", "x": 0.8, "y": 0.55, "region": "east"},
    {"id": "pittsburgh", "name": "Pittsburgh", "x": 0.7, "y": 0.5, "region": "east"},
    {"id": "chicago", "name": "Chicago", "x": 0.55, "y": 0.4, "region": "east"},
    {"id": "raleigh", "name": "Raleigh", "x": 0.75, "y": 0.6, "region": "east"},
]

# Routes data - matching the Flutter app routes
GAME_ROUTES = [
    # Western Routes
    {"id": "route_0", "from_city_id": "vancouver", "to_city_id": "calgary", "length": 3, "color": "gray", "points": 4},
    {"id": "route_1", "from_city_id": "calgary", "to_city_id": "helena", "length": 4, "color": "gray", "points": 7},
    {"id": "route_2", "from_city_id": "helena", "to_city_id": "winnipeg", "length": 4, "color": "blue", "points": 7},
    {"id": "route_3", "from_city_id": "winnipeg", "to_city_id": "duluth", "length": 4, "color": "gray", "points": 7},
    {"id": "route_4", "from_city_id": "vancouver", "to_city_id": "seattle", "length": 1, "color": "gray", "points": 1},
    {"id": "route_5", "from_city_id": "seattle", "to_city_id": "portland", "length": 1, "color": "gray", "points": 1},
    {"id": "route_6", "from_city_id": "portland", "to_city_id": "san_francisco", "length": 5, "color": "green", "points": 10},
    {"id": "route_7", "from_city_id": "san_francisco", "to_city_id": "los_angeles", "length": 3, "color": "yellow", "points": 4},
    {"id": "route_8", "from_city_id": "los_angeles", "to_city_id": "las_vegas", "length": 2, "color": "gray", "points": 2},
    {"id": "route_9", "from_city_id": "las_vegas", "to_city_id": "salt_lake_city", "length": 3, "color": "orange", "points": 4},
    {"id": "route_10", "from_city_id": "salt_lake_city", "to_city_id": "denver", "length": 3, "color": "red", "points": 4},
    {"id": "route_11", "from_city_id": "los_angeles", "to_city_id": "phoenix", "length": 6, "color": "gray", "points": 15},
    {"id": "route_12", "from_city_id": "phoenix", "to_city_id": "santa_fe", "length": 3, "color": "gray", "points": 4},
    {"id": "route_13", "from_city_id": "santa_fe", "to_city_id": "el_paso", "length": 2, "color": "gray", "points": 2},
    
    # Central Routes
    {"id": "route_14", "from_city_id": "denver", "to_city_id": "kansas_city", "length": 4, "color": "black", "points": 7},
    {"id": "route_15", "from_city_id": "kansas_city", "to_city_id": "oklahoma_city", "length": 2, "color": "gray", "points": 2},
    {"id": "route_16", "from_city_id": "oklahoma_city", "to_city_id": "dallas", "length": 2, "color": "gray", "points": 2},
    {"id": "route_17", "from_city_id": "dallas", "to_city_id": "houston", "length": 1, "color": "gray", "points": 1},
    {"id": "route_18", "from_city_id": "oklahoma_city", "to_city_id": "little_rock", "length": 2, "color": "gray", "points": 2},
    {"id": "route_19", "from_city_id": "little_rock", "to_city_id": "new_orleans", "length": 3, "color": "green", "points": 4},
    {"id": "route_20", "from_city_id": "little_rock", "to_city_id": "nashville", "length": 3, "color": "white", "points": 4},
    {"id": "route_21", "from_city_id": "nashville", "to_city_id": "atlanta", "length": 1, "color": "gray", "points": 1},
    {"id": "route_22", "from_city_id": "atlanta", "to_city_id": "charleston", "length": 2, "color": "gray", "points": 2},
    {"id": "route_23", "from_city_id": "charleston", "to_city_id": "miami", "length": 4, "color": "pink", "points": 7},
    
    # Eastern Routes
    {"id": "route_24", "from_city_id": "duluth", "to_city_id": "sault_st_marie", "length": 3, "color": "gray", "points": 4},
    {"id": "route_25", "from_city_id": "sault_st_marie", "to_city_id": "toronto", "length": 2, "color": "gray", "points": 2},
    {"id": "route_26", "from_city_id": "toronto", "to_city_id": "montreal", "length": 3, "color": "gray", "points": 4},
    {"id": "route_27", "from_city_id": "montreal", "to_city_id": "boston", "length": 2, "color": "gray", "points": 2},
    {"id": "route_28", "from_city_id": "boston", "to_city_id": "new_york", "length": 2, "color": "yellow", "points": 2},
    {"id": "route_29", "from_city_id": "new_york", "to_city_id": "washington", "length": 2, "color": "orange", "points": 2},
    {"id": "route_30", "from_city_id": "washington", "to_city_id": "pittsburgh", "length": 2, "color": "gray", "points": 2},
    {"id": "route_31", "from_city_id": "pittsburgh", "to_city_id": "chicago", "length": 3, "color": "black", "points": 4},
    {"id": "route_32", "from_city_id": "washington", "to_city_id": "raleigh", "length": 2, "color": "gray", "points": 2},
    
    # Cross-country routes
    {"id": "route_33", "from_city_id": "helena", "to_city_id": "denver", "length": 4, "color": "green", "points": 7},
    {"id": "route_34", "from_city_id": "denver", "to_city_id": "kansas_city", "length": 4, "color": "orange", "points": 7},
    {"id": "route_35", "from_city_id": "kansas_city", "to_city_id": "chicago", "length": 2, "color": "blue", "points": 2},
    {"id": "route_36", "from_city_id": "chicago", "to_city_id": "pittsburgh", "length": 3, "color": "orange", "points": 4},
    {"id": "route_37", "from_city_id": "pittsburgh", "to_city_id": "washington", "length": 2, "color": "gray", "points": 2},
    {"id": "route_38", "from_city_id": "washington", "to_city_id": "new_york", "length": 2, "color": "black", "points": 2},
    {"id": "route_39", "from_city_id": "new_york", "to_city_id": "boston", "length": 2, "color": "red", "points": 2},
    
    # Double routes (parallel routes between same cities)
    {"id": "route_40", "from_city_id": "seattle", "to_city_id": "helena", "length": 6, "color": "pink", "points": 15, "is_double_route": True, "double_route_id": "route_41"},
    {"id": "route_41", "from_city_id": "seattle", "to_city_id": "helena", "length": 6, "color": "white", "points": 15, "is_double_route": True, "double_route_id": "route_40"},
    {"id": "route_42", "from_city_id": "duluth", "to_city_id": "chicago", "length": 3, "color": "red", "points": 4, "is_double_route": True, "double_route_id": "route_43"},
    {"id": "route_43", "from_city_id": "duluth", "to_city_id": "chicago", "length": 3, "color": "white", "points": 4, "is_double_route": True, "double_route_id": "route_42"},
    {"id": "route_44", "from_city_id": "toronto", "to_city_id": "chicago", "length": 4, "color": "white", "points": 7, "is_double_route": True, "double_route_id": "route_45"},
    {"id": "route_45", "from_city_id": "toronto", "to_city_id": "chicago", "length": 4, "color": "pink", "points": 7, "is_double_route": True, "double_route_id": "route_44"},
    {"id": "route_46", "from_city_id": "new_york", "to_city_id": "washington", "length": 2, "color": "black", "points": 2, "is_double_route": True, "double_route_id": "route_47"},
    {"id": "route_47", "from_city_id": "new_york", "to_city_id": "washington", "length": 2, "color": "orange", "points": 2, "is_double_route": True, "double_route_id": "route_46"},
    
    # Additional routes to reach over 50 total
    {"id": "route_48", "from_city_id": "vancouver", "to_city_id": "helena", "length": 6, "color": "yellow", "points": 15},
    {"id": "route_49", "from_city_id": "seattle", "to_city_id": "salt_lake_city", "length": 3, "color": "white", "points": 4},
    {"id": "route_50", "from_city_id": "portland", "to_city_id": "salt_lake_city", "length": 6, "color": "blue", "points": 15},
    {"id": "route_51", "from_city_id": "san_francisco", "to_city_id": "denver", "length": 5, "color": "red", "points": 10},
    {"id": "route_52", "from_city_id": "los_angeles", "to_city_id": "phoenix", "length": 3, "color": "yellow", "points": 4},
    {"id": "route_53", "from_city_id": "las_vegas", "to_city_id": "phoenix", "length": 3, "color": "orange", "points": 4},
    {"id": "route_54", "from_city_id": "los_angeles", "to_city_id": "new_york", "length": 6, "color": "pink", "points": 15},
]

# Train cards data - matching Flutter app
TRAIN_CARDS = [
    {"color": "red", "count": 12, "is_locomotive": False},
    {"color": "blue", "count": 12, "is_locomotive": False},
    {"color": "green", "count": 12, "is_locomotive": False},
    {"color": "yellow", "count": 12, "is_locomotive": False},
    {"color": "orange", "count": 12, "is_locomotive": False},
    {"color": "pink", "count": 12, "is_locomotive": False},
    {"color": "white", "count": 12, "is_locomotive": False},
    {"color": "black", "count": 12, "is_locomotive": False},
    {"color": "gray", "count": 12, "is_locomotive": False},
    {"color": "wild", "count": 14, "is_locomotive": True}  # Locomotives are wild cards
]

# Destination tickets data - using only cities that exist in our cities list
DESTINATION_TICKETS = [
    {"from_city_id": "vancouver", "to_city_id": "montreal", "points": 20, "penalty": 20},
    {"from_city_id": "vancouver", "to_city_id": "santa_fe", "points": 13, "penalty": 13},
    {"from_city_id": "vancouver", "to_city_id": "atlanta", "points": 17, "penalty": 17},
    {"from_city_id": "calgary", "to_city_id": "phoenix", "points": 13, "penalty": 13},
    {"from_city_id": "calgary", "to_city_id": "salt_lake_city", "points": 7, "penalty": 7},
    {"from_city_id": "calgary", "to_city_id": "oklahoma_city", "points": 15, "penalty": 15},
    {"from_city_id": "winnipeg", "to_city_id": "little_rock", "points": 11, "penalty": 11},
    {"from_city_id": "winnipeg", "to_city_id": "houston", "points": 12, "penalty": 12},
    {"from_city_id": "winnipeg", "to_city_id": "new_orleans", "points": 12, "penalty": 12},
    {"from_city_id": "sault_st_marie", "to_city_id": "nashville", "points": 8, "penalty": 8},
    {"from_city_id": "sault_st_marie", "to_city_id": "oklahoma_city", "points": 9, "penalty": 9},
    {"from_city_id": "montreal", "to_city_id": "atlanta", "points": 9, "penalty": 9},
    {"from_city_id": "montreal", "to_city_id": "new_orleans", "points": 13, "penalty": 13},
    {"from_city_id": "boston", "to_city_id": "miami", "points": 12, "penalty": 12},
    {"from_city_id": "new_york", "to_city_id": "atlanta", "points": 6, "penalty": 6},
    {"from_city_id": "new_york", "to_city_id": "miami", "points": 10, "penalty": 10},
    {"from_city_id": "washington", "to_city_id": "miami", "points": 9, "penalty": 9},
    {"from_city_id": "washington", "to_city_id": "nashville", "points": 7, "penalty": 7},
    {"from_city_id": "raleigh", "to_city_id": "new_orleans", "points": 7, "penalty": 7},
    {"from_city_id": "charleston", "to_city_id": "phoenix", "points": 18, "penalty": 18},
    {"from_city_id": "atlanta", "to_city_id": "miami", "points": 5, "penalty": 5},
    {"from_city_id": "atlanta", "to_city_id": "charleston", "points": 2, "penalty": 2},
    {"from_city_id": "miami", "to_city_id": "new_orleans", "points": 6, "penalty": 6},
    {"from_city_id": "new_orleans", "to_city_id": "houston", "points": 2, "penalty": 2},
    {"from_city_id": "houston", "to_city_id": "dallas", "points": 1, "penalty": 1},
    {"from_city_id": "dallas", "to_city_id": "oklahoma_city", "points": 2, "penalty": 2},
    {"from_city_id": "dallas", "to_city_id": "little_rock", "points": 2, "penalty": 2},
    {"from_city_id": "oklahoma_city", "to_city_id": "kansas_city", "points": 2, "penalty": 2},
    {"from_city_id": "kansas_city", "to_city_id": "chicago", "points": 3, "penalty": 3},
    {"from_city_id": "duluth", "to_city_id": "winnipeg", "points": 4, "penalty": 4},
    {"from_city_id": "duluth", "to_city_id": "sault_st_marie", "points": 3, "penalty": 3},
    {"from_city_id": "winnipeg", "to_city_id": "sault_st_marie", "points": 6, "penalty": 6},
    {"from_city_id": "sault_st_marie", "to_city_id": "toronto", "points": 2, "penalty": 2},
    {"from_city_id": "sault_st_marie", "to_city_id": "montreal", "points": 5, "penalty": 5},
    {"from_city_id": "toronto", "to_city_id": "montreal", "points": 3, "penalty": 3},
    {"from_city_id": "toronto", "to_city_id": "chicago", "points": 4, "penalty": 4},
    {"from_city_id": "toronto", "to_city_id": "pittsburgh", "points": 2, "penalty": 2},
    {"from_city_id": "chicago", "to_city_id": "pittsburgh", "points": 3, "penalty": 3},
    {"from_city_id": "pittsburgh", "to_city_id": "washington", "points": 2, "penalty": 2},
    {"from_city_id": "pittsburgh", "to_city_id": "nashville", "points": 4, "penalty": 4},
    {"from_city_id": "pittsburgh", "to_city_id": "raleigh", "points": 2, "penalty": 2},
    {"from_city_id": "washington", "to_city_id": "new_york", "points": 2, "penalty": 2},
    {"from_city_id": "washington", "to_city_id": "raleigh", "points": 2, "penalty": 2},
    {"from_city_id": "new_york", "to_city_id": "boston", "points": 2, "penalty": 2},
    {"from_city_id": "new_york", "to_city_id": "montreal", "points": 3, "penalty": 3},
    {"from_city_id": "boston", "to_city_id": "montreal", "points": 2, "penalty": 2},
    {"from_city_id": "raleigh", "to_city_id": "charleston", "points": 2, "penalty": 2},
    {"from_city_id": "raleigh", "to_city_id": "atlanta", "points": 2, "penalty": 2},
    {"from_city_id": "charleston", "to_city_id": "atlanta", "points": 2, "penalty": 2},
    {"from_city_id": "charleston", "to_city_id": "miami", "points": 4, "penalty": 4},
    {"from_city_id": "atlanta", "to_city_id": "nashville", "points": 1, "penalty": 1},
    {"from_city_id": "nashville", "to_city_id": "little_rock", "points": 3, "penalty": 3},
    {"from_city_id": "little_rock", "to_city_id": "oklahoma_city", "points": 2, "penalty": 2},
    {"from_city_id": "little_rock", "to_city_id": "dallas", "points": 2, "penalty": 2},
    {"from_city_id": "oklahoma_city", "to_city_id": "santa_fe", "points": 3, "penalty": 3},
    {"from_city_id": "santa_fe", "to_city_id": "denver", "points": 2, "penalty": 2},
    {"from_city_id": "santa_fe", "to_city_id": "phoenix", "points": 3, "penalty": 3},
    {"from_city_id": "denver", "to_city_id": "helena", "points": 4, "penalty": 4},
    {"from_city_id": "denver", "to_city_id": "kansas_city", "points": 4, "penalty": 4},
    {"from_city_id": "helena", "to_city_id": "salt_lake_city", "points": 3, "penalty": 3},
    {"from_city_id": "helena", "to_city_id": "duluth", "points": 6, "penalty": 6},
    {"from_city_id": "salt_lake_city", "to_city_id": "portland", "points": 6, "penalty": 6},
    {"from_city_id": "salt_lake_city", "to_city_id": "san_francisco", "points": 5, "penalty": 5},
    {"from_city_id": "portland", "to_city_id": "san_francisco", "points": 5, "penalty": 5},
    {"from_city_id": "portland", "to_city_id": "seattle", "points": 1, "penalty": 1},
    {"from_city_id": "san_francisco", "to_city_id": "los_angeles", "points": 3, "penalty": 3},
    {"from_city_id": "los_angeles", "to_city_id": "las_vegas", "points": 2, "penalty": 2},
    {"from_city_id": "los_angeles", "to_city_id": "phoenix", "points": 3, "penalty": 3},
    {"from_city_id": "las_vegas", "to_city_id": "phoenix", "points": 3, "penalty": 3},
    {"from_city_id": "phoenix", "to_city_id": "denver", "points": 5, "penalty": 5},
    {"from_city_id": "seattle", "to_city_id": "helena", "points": 6, "penalty": 6},
    {"from_city_id": "seattle", "to_city_id": "vancouver", "points": 1, "penalty": 1}
]
